index/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
path('', index, name='index'),
path('logout/', out, name='logout'),
path('login', enter, name='enter'),
path('profile/', profile, name='profile'),
path('change/', change, name='change'),
path('audit/', useraudit, name='audit'),
path('vote/', vote, name='vote'),
path('sendotp/', sendotp, name='sendotp'),
path('checkotp/', checkotp, name='checkotp'),
path('receivedata/', receivedata, name='receivedata'),
path('results/', userresults, name='userresults'),
path('update/', update, name='update'),
path('logout/', out, name='logout'),
path("createuser", createadmin, name="createuser")
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('administrator/', include('useradmin.urls')),
]

index/models.py
from django.db import models
class Otp(models.Model):
	RegNo=models.CharField(max_length=50)
	Code=models.CharField(max_length=50)
class Election(models.Model):
	Year=models.IntegerField()
	Status=models.CharField(max_length=50, null=True)
	Start=models.DateTimeField(null=True)
	End=models.DateTimeField(null=True)
	Type=models.CharField(max_length=50, null=True)
	def __str__(self):
		return self.Type
class Voter(models.Model):
	RegNo=models.CharField(max_length=50)
	FirstName=models.CharField(max_length=60)
	LastName=models.CharField(max_length=50)
	School=models.CharField(max_length=50)
	Email=models.CharField(max_length=60)
	Number=models.CharField(max_length=50)
	Leader=models.BooleanField(default=False)
	Cohort=models.CharField(max_length=50, null=True)
	Activated=models.BooleanField(default=False)
	Year=models.IntegerField(null=True)
	Eligible=models.BooleanField(default=True)
	Explanation=models.TextField(null=True)
	def __str__(self):
		return self.RegNo
class Post(models.Model):
	Election=models.ForeignKey(Election, on_delete=models.CASCADE, 	null=True)
	Name=models.CharField(max_length=60)
	Type=models.CharField(max_length=50)
	def __str__(self):
		return self.Name
class Contestant(models.Model):
	Individual=models.ForeignKey(Voter, on_delete=models.CASCADE)
	Post=models.ForeignKey(Post, on_delete=models.CASCADE)
	Votes=models.IntegerField()
	Pic=models.ImageField(null=True)
	def __str__(self):
		return self.Individual.RegNo
class Vote(models.Model):
	Voter=models.ForeignKey(Voter, on_delete=models.CASCADE)
	Contestant=models.ForeignKey(Contestant, on_delete=models.CASCADE)
	Date=models.DateField()
	Time=models.TimeField()
	Election=models.ForeignKey(Election, on_delete=models.CASCADE, null=True)
	Key=models.CharField(max_length=50, null=True)
	def __str__(self):
		return self.Key
class School(models.Model):
	Initials=models.CharField(max_length=15)
	Name=models.CharField(max_length=60)
	def __str__(self):
		return self.Name
class StudentCvs(models.Model):
	Name=models.CharField(max_length=70,)
	File=models.FileField(max_length=1000, upload_to='files')
		

templates/user/audit.html
{%extends 'user/base.html'%}
{%block content%}
{%load tags%}
{%load static%}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10 col-12 my-2">
      <div class="card">
        <div class="card-header">
          {%if error%}
          <div class="alert alert-warning">
            {{error}}
          </div>
          {%else%}
          <div class="card-body">
            <caption>
              <center><img src="{%static 'images/tsa.jpg'%}" class="img img-responsive" width="80px;"><br>Audit for 2022 Elections</center>
            </caption>
            <table class="table table-sm table-bordered table-responsive-sm table-condensed">
              {%for x in posts|content%}
              <thead><th colspan="4" class="text-center">{{x.Name}}</th></thead>
              <thead>
                <th>Position</th>
                <th>Name</th>
                <th>RegNo</th>
                <th>Votes</th>
              </thead>
              {%for y in x.contestant_set.all|sort%}
              <thead>
                <th>{{forloop.counter}}</th>
                <th>{{y.Individual.FirstName}} {{y.Individual.LastName}}</th>
                <th>{{y.Individual.RegNo}}</th>
                <th>{{y.Votes}}</th>
              </thead>
              <tr><td colspan="4"><center>Secret Keys...</center></td></tr>
              <thead>
                <th>Number</th>
                <th>Key</th>
                <th>Date</th>
              </thead>
              {%for vote in y.vote_set.all%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{vote.Key}}</td>
                <td>{{vote.Date}}</td>
              </tr>
              {%endfor%}
              {%endfor%}
              {%endfor%}
            </table>
          </div>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock content%}

templates/user/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>TSA -Voting Student</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no,maximum-scale=1.0, user-scalable=0">
		<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{%static 'css/style.css' %}">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel = "icon" href ="{%static 'images/tsa.jpg'%}" 
        type = "image/x-icon">
          
</head>
<body class="bg-light">
		    <script type="text/javascript" src="{%static 'js/Chart.js'%}"></script>	
		        <script src="{%static 'js/jquery.min.js' %}"></script>
    <script src="{%static 'js/popper.js' %}"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
	{%include 'user/navbar.html'%}
	{%block content%}
	{%endblock content%}
	<div class="card">
		<div class="card-body text-success text-center">
			<p>Site Build by <b>Projects Committee 2021/2022</b></p>
		</div>
	</div>
</body>

templates/user/dash.html
{%extends 'user/base.html'%}
{%load tags%}
{%block content%}
<div class="container my-2">
	{%if election%}
	<center>Welcome to the {{election.Year}} TSA Elections!</center>
	{%if voted%}
	<div class="row justify-content-center">
		<div class="col-md-4 col-12">
			<div class="alert alert-info">
				You have already Voted in this election! Check the live results!
			</div>
		</div>
	</div>
	{%else%}
	<div class="row justify-content-center">
		<form class="needs-validation w-100" method="POST" action="{%url 'vote'%}" >
			{%csrf_token%}
		<div class="row">
			{%for x in posts|content%}
			<div class="col-12 col-md-6 mx-1">
				<p><b>{{forloop.counter}}.Vote for {{x.Type}} {{x.Name}}</b></p>
				{%for y in x.contestant_set.all%}
				<div class="form-check">
				 <input id="{{y.id}}" class="form-check-input"  type="radio" name="p{{y.Post.id}}" value="{{y.id}}" required="">
				 <label class="form-check-radio"  for="{{y.id}}">{{y.Individual.FirstName}} {{y.Individual.LastName}} </label>
				</div>
				 {%endfor %}
			</div>
			{%endfor%}
		</div>
		<div class="my-2 col-md-4 col-12">
			<button class="btn btn-block btn-info rounded-pill">
				Vote!
			</button>
		</div>
		</form>
	</div>
	{%endif%}
	{%else%}
	<div class="row justify-content-center">
		<div class="col-md-4 col-12">
			<div class="alert alert-info">
				There is no ongoing election! Check the results!
			</div>
		</div>
	</div>
	{%endif%}
	<div class="row justify-content-center">
		<div class="col-12 col-md-4">
			<div class="card">
				<div class="card-header bg-primary">
					My Personal Data
				</div>
				<div class="card-body">
					<div class="card-text">
						<b>Reg No: </b> {{voter.RegNo}}<br>
						<b>Name  : </b> {{voter.FirstName}} {{voter.LastName}}<br>
						<b>School: </b> {{voter.School}}<br>
						<b>Email : </b> {{voter.Email}}<br>
						Eligible to vote...
						<span class="badge badge-pill badge-success">Yes</span>
					</div>
				</div>
			</div>
		</div>
	</div>
<div class="row">
	<div class="col-12">
      <div class="card my-1 border-success">
        <div class="card-body">
          <b>How to Vote</b> <br>
          Welcome to the TSA 2022 Elections !<br>
          To Vote Please follow this 4 steps..<br>
          1. Login to the voting portal with the password send to your email..<br>
          2. If Voting is on choose your prefered candidates and click vote...<br>
          3. You will receive an email with your unique secret code.<br>
          4. Once voting is done access results to see who won. To confirm the results are correct click on audit and check for your secret code under the contestant you voted for
        </div>
      </div>
	</div>
</div>
</div>
{%endblock content%}

templates/user/navbar.html
{%load static%}
    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: rgb(0, 100, 0);">
        <a href="#" class="navbar-brand"><b><span class="text-dark">Hello</span><span class="text-dark"> {{request.user.username}}</span></b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#Menu4">
            <span class="navbar-toggler-icon"></span>
        </button>  
        <div class="collapse navbar-collapse"  id="Menu4">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'index'%}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'userresults'%}">Results</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'audit'%}">Audit Results</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'index'%}">Leaders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'change'%}">Reset</a>
                </li>  
            </ul>
        </div>
    </nav>

templates/user/reset.html
{%extends 'user/base.html'%}
{%block content%}
<div class="container">
	<div class="row d-flex justify-content-center">
		<div class="col-md-4 col-12">
			<div class="card shadow">
				<div class="card-header text-white bg-info">
					<b>Change Password</b>
				</div>
				<div class="card-body">
				    {%if error%}
                    <div class="card-text">
                        <div class="alert alert-warning">
                            {{error}}
                        </div>
                    </div>
                    {%endif%}
				<form method="POST" class="needs-validation my-3">
					{%csrf_token%}
					<label>Old Password</label>
					<input type="password" name="oldpass" class="form-control rounded-pill my-2" required="">
					<label>New Password</label>
					<input type="password" name="newpass" class="form-control rounded-pill my-2" id="password" required="">
					<label>Confirm New Password</label>
					<input type="password" name="confirm" class="form-control rounded-pill my-2" id="pass2" required=""> 
					<button class="btn btn-block btn-info rounded-pill" type="submit">Change</button>
				</form>			
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	    $("#pass2").change(function(e){
        e.preventDefault();
        var password1= $("#password").val();
        var password2= $(this).val();
        if(password1 !== password2){
        alert("Error! passwords dont match")
        document.getElementById("pass2").value="";
        document.getElementById("password").value="";
        }
    });
</script>
{%endblock content%}

templates/user/results.html
{%extends 'user/base.html'%}
{%block content%}
{%load tags%}
{%load static%}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10 col-12 my-2">
      <div class="card">
        <div class="card-header">
          {%if error%}
          <div class="alert alert-warning">
            {{error}}
          </div>
          {%else%}
          <div class="card-body">
            <a href="{%url 'audit'%}"><button class="btn btn-primary rounded-pill">Audit</button></a>
            <caption>
              <center><img src="{%static 'images/logo.png'%}" class="img img-responsive" width="80px;"><br>Results for 2021 Elections</center>
            </caption>
            <table class="table table-sm table-striped table-bordered table-responsive-sm table-condensed">
              {%for x in posts|content%}
              <thead><th colspan="4" class="text-center">{{x.Type}} {{x.Name}}</th></thead>
              <thead>
                <th>Position</th>
                <th>Name</th>
                <th>RegNo</th>
                <th>Votes</th>
              </thead>
              {%for y in x.contestant_set.all|sort%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{y.Individual.FirstName}} {{y.Individual.LastName}}</td>
                <td>{{y.Individual.RegNo}}</td>
                <td>{{y.Votes}}</td>
              </tr>
              {%endfor%}
              {%endfor%}
            </table>
          </div>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock content%}

templates/user/success.html
{%extends 'user/base.html'%}
{%block content%}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4 col-12">
			<div class="my-2 alert alert-success">
				You have successfully voted! Viva to Comrade Power!
			</div>
			<div class="my-2">
				<div class="card">
					<div class="card-header">
						<b>Here are Your Choices.</b>
					</div>
					<div class="card-body">
						{%for x in cons%}
						<p><b>For {{x.Contestant.Post.Type}} {{x.Contestant.Post.Name}}</b></p>
						<p>{{x.Contestant.Individual.FirstName}} {{x.Contestant.Individual.LastName}}</p>
						{%endfor%}
						<p>Your Secret Code is {{secret}}</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{%endblock content%}